# 设置项目名称
name: destiny

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: destiny-web:latest
    container_name: destiny-web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=rm-bp1455j4m154h13ydto.mysql.rds.aliyuncs.com
      - DB_PORT=3306
      - DB_USER=kk
      - DB_PASSWORD=kk123_456
      - DB_NAME=destiny
      - OLLAMA_URL=http://kkteam.online:10434/api/generate
    volumes:
      - ..:/app
    restart: unless-stopped